service: cs-group-${self:custom.stageVars.groupNumber}-${self:custom.stageVars.myFirstname}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - 'Fn::GetAtt': [Table, Arn]
  environment:
    tableName: ${self:service.name}-dynamodb

functions:
  hello:
    handler: functions/hello.handle
    events:
      - http:
          path: hello
          method: get

  get_movie:
    handler: functions/get_movie.handle
    events:
      - http:
          method: get
          path: movies/{id}
          cors:
            origin: 'http://localhost:3000'
            allowCredentials: true

  create_movie:
    handler: functions/create_movie.handle
    events:
      - http:
          method: post
          path: movies
          cors:
            origin: 'http://localhost:3000'
            allowCredentials: true

  list_movies:
    handler: functions/list_movies.handle
    events:
      - http:
          method: get
          path: movies
          cors:
            origin: 'http://localhost:3000'
            allowCredentials: true

  list_users:
    handler: functions/list_users.handle
    events:
      - http:
          method : get
          path: users
          cors:
            origin: 'http://localhost:3000'
            allowCredentials : true

  put_user_rating:
    handler: functions/put_user_rating.handle
    events:
      - http:
          method : put
          path: users
          cors:
            origin: 'http://localhost:3000'
            allowCredentials : true

  get_average:
    handler: functions/get_average.handle
    events:
      - http:
          method : post
          path: average
          cors:
            origin: 'http://localhost:3000'
            allowCredentials : true

            
custom:
  stageVars: ${file(./stage.${self:provider.stage}.yml)}

resources:
  - ${file(resources/dynamodb.yml)}
