aws dynamodb batch-write-item --request-items file://movies_0.json
aws dynamodb batch-write-item --request-items file://movies_1.json
aws dynamodb batch-write-item --request-items file://movies_2.json
aws dynamodb batch-write-item --request-items file://movies_3.json
aws dynamodb batch-write-item --request-items file://movies_4.json
aws dynamodb batch-write-item --request-items file://movies_5.json
aws dynamodb batch-write-item --request-items file://movies_6.json
aws dynamodb batch-write-item --request-items file://movies_7.json
aws dynamodb batch-write-item --request-items file://movies_8.json
aws dynamodb batch-write-item --request-items file://movies_9.json
aws dynamodb batch-write-item --request-items file://movies_10.json
aws dynamodb batch-write-item --request-items file://movies_11.json
aws dynamodb batch-write-item --request-items file://movies_12.json
aws dynamodb batch-write-item --request-items file://movies_13.json
aws dynamodb batch-write-item --request-items file://movies_14.json
aws dynamodb batch-write-item --request-items file://movies_15.json
aws dynamodb batch-write-item --request-items file://movies_16.json
aws dynamodb batch-write-item --request-items file://movies_17.json
aws dynamodb batch-write-item --request-items file://movies_18.json
aws dynamodb batch-write-item --request-items file://movies_19.json
aws dynamodb batch-write-item --request-items file://movies_20.json
aws dynamodb batch-write-item --request-items file://movies_21.json
aws dynamodb batch-write-item --request-items file://movies_22.json
aws dynamodb batch-write-item --request-items file://movies_23.json
aws dynamodb batch-write-item --request-items file://movies_24.json
aws dynamodb batch-write-item --request-items file://movies_25.json
aws dynamodb batch-write-item --request-items file://movies_26.json
aws dynamodb batch-write-item --request-items file://movies_27.json
aws dynamodb batch-write-item --request-items file://movies_28.json
aws dynamodb batch-write-item --request-items file://movies_29.json
aws dynamodb batch-write-item --request-items file://movies_30.json
aws dynamodb batch-write-item --request-items file://movies_31.json
aws dynamodb batch-write-item --request-items file://movies_32.json
aws dynamodb batch-write-item --request-items file://movies_33.json
aws dynamodb batch-write-item --request-items file://movies_34.json
aws dynamodb batch-write-item --request-items file://movies_35.json
aws dynamodb batch-write-item --request-items file://movies_36.json
aws dynamodb batch-write-item --request-items file://movies_37.json
aws dynamodb batch-write-item --request-items file://movies_38.json
aws dynamodb batch-write-item --request-items file://movies_39.json
aws dynamodb batch-write-item --request-items file://movies_40.json
aws dynamodb batch-write-item --request-items file://movies_41.json
aws dynamodb batch-write-item --request-items file://movies_42.json
aws dynamodb batch-write-item --request-items file://movies_43.json
aws dynamodb batch-write-item --request-items file://movies_44.json
aws dynamodb batch-write-item --request-items file://movies_45.json
aws dynamodb batch-write-item --request-items file://movies_46.json
aws dynamodb batch-write-item --request-items file://movies_47.json
aws dynamodb batch-write-item --request-items file://movies_48.json
aws dynamodb batch-write-item --request-items file://movies_49.json
aws dynamodb batch-write-item --request-items file://movies_50.json
aws dynamodb batch-write-item --request-items file://movies_51.json
aws dynamodb batch-write-item --request-items file://movies_52.json
aws dynamodb batch-write-item --request-items file://movies_53.json
aws dynamodb batch-write-item --request-items file://movies_54.json
aws dynamodb batch-write-item --request-items file://movies_55.json
aws dynamodb batch-write-item --request-items file://movies_56.json
aws dynamodb batch-write-item --request-items file://movies_57.json
aws dynamodb batch-write-item --request-items file://movies_58.json
aws dynamodb batch-write-item --request-items file://movies_59.json
aws dynamodb batch-write-item --request-items file://movies_60.json
aws dynamodb batch-write-item --request-items file://movies_61.json
aws dynamodb batch-write-item --request-items file://movies_62.json
aws dynamodb batch-write-item --request-items file://movies_63.json
aws dynamodb batch-write-item --request-items file://movies_64.json
aws dynamodb batch-write-item --request-items file://movies_65.json
aws dynamodb batch-write-item --request-items file://movies_66.json
aws dynamodb batch-write-item --request-items file://movies_67.json
aws dynamodb batch-write-item --request-items file://movies_68.json
aws dynamodb batch-write-item --request-items file://movies_69.json
aws dynamodb batch-write-item --request-items file://movies_70.json
aws dynamodb batch-write-item --request-items file://movies_71.json
aws dynamodb batch-write-item --request-items file://movies_72.json
aws dynamodb batch-write-item --request-items file://movies_73.json
aws dynamodb batch-write-item --request-items file://movies_74.json
aws dynamodb batch-write-item --request-items file://movies_75.json
aws dynamodb batch-write-item --request-items file://movies_76.json
aws dynamodb batch-write-item --request-items file://movies_77.json
aws dynamodb batch-write-item --request-items file://movies_78.json
aws dynamodb batch-write-item --request-items file://movies_79.json
aws dynamodb batch-write-item --request-items file://movies_80.json
aws dynamodb batch-write-item --request-items file://movies_81.json
aws dynamodb batch-write-item --request-items file://movies_82.json
aws dynamodb batch-write-item --request-items file://movies_83.json
aws dynamodb batch-write-item --request-items file://movies_84.json
aws dynamodb batch-write-item --request-items file://movies_85.json
aws dynamodb batch-write-item --request-items file://movies_86.json
aws dynamodb batch-write-item --request-items file://movies_87.json
aws dynamodb batch-write-item --request-items file://movies_88.json
aws dynamodb batch-write-item --request-items file://movies_89.json
aws dynamodb batch-write-item --request-items file://movies_90.json
aws dynamodb batch-write-item --request-items file://movies_91.json
aws dynamodb batch-write-item --request-items file://movies_92.json
aws dynamodb batch-write-item --request-items file://movies_93.json
aws dynamodb batch-write-item --request-items file://movies_94.json
aws dynamodb batch-write-item --request-items file://movies_95.json
aws dynamodb batch-write-item --request-items file://movies_96.json
aws dynamodb batch-write-item --request-items file://movies_97.json
aws dynamodb batch-write-item --request-items file://movies_98.json
aws dynamodb batch-write-item --request-items file://movies_99.json
aws dynamodb batch-write-item --request-items file://movies_100.json
aws dynamodb batch-write-item --request-items file://movies_101.json
aws dynamodb batch-write-item --request-items file://movies_102.json
aws dynamodb batch-write-item --request-items file://movies_103.json
aws dynamodb batch-write-item --request-items file://movies_104.json
aws dynamodb batch-write-item --request-items file://movies_105.json
aws dynamodb batch-write-item --request-items file://movies_106.json
aws dynamodb batch-write-item --request-items file://movies_107.json
aws dynamodb batch-write-item --request-items file://movies_108.json
aws dynamodb batch-write-item --request-items file://movies_109.json
aws dynamodb batch-write-item --request-items file://movies_110.json
aws dynamodb batch-write-item --request-items file://movies_111.json
aws dynamodb batch-write-item --request-items file://movies_112.json
aws dynamodb batch-write-item --request-items file://movies_113.json
aws dynamodb batch-write-item --request-items file://movies_114.json
aws dynamodb batch-write-item --request-items file://movies_115.json
aws dynamodb batch-write-item --request-items file://movies_116.json
aws dynamodb batch-write-item --request-items file://movies_117.json
aws dynamodb batch-write-item --request-items file://movies_118.json
aws dynamodb batch-write-item --request-items file://movies_119.json
aws dynamodb batch-write-item --request-items file://movies_120.json
aws dynamodb batch-write-item --request-items file://movies_121.json
aws dynamodb batch-write-item --request-items file://movies_122.json
aws dynamodb batch-write-item --request-items file://movies_123.json
aws dynamodb batch-write-item --request-items file://movies_124.json
aws dynamodb batch-write-item --request-items file://movies_125.json
aws dynamodb batch-write-item --request-items file://movies_126.json
aws dynamodb batch-write-item --request-items file://movies_127.json
aws dynamodb batch-write-item --request-items file://movies_128.json
aws dynamodb batch-write-item --request-items file://movies_129.json
aws dynamodb batch-write-item --request-items file://movies_130.json
aws dynamodb batch-write-item --request-items file://movies_131.json
aws dynamodb batch-write-item --request-items file://movies_132.json
aws dynamodb batch-write-item --request-items file://movies_133.json
aws dynamodb batch-write-item --request-items file://movies_134.json
aws dynamodb batch-write-item --request-items file://movies_135.json
aws dynamodb batch-write-item --request-items file://movies_136.json
aws dynamodb batch-write-item --request-items file://movies_137.json
aws dynamodb batch-write-item --request-items file://movies_138.json
aws dynamodb batch-write-item --request-items file://movies_139.json
aws dynamodb batch-write-item --request-items file://movies_140.json
aws dynamodb batch-write-item --request-items file://movies_141.json
aws dynamodb batch-write-item --request-items file://movies_142.json
aws dynamodb batch-write-item --request-items file://movies_143.json
aws dynamodb batch-write-item --request-items file://movies_144.json
aws dynamodb batch-write-item --request-items file://movies_145.json
aws dynamodb batch-write-item --request-items file://movies_146.json
aws dynamodb batch-write-item --request-items file://movies_147.json
aws dynamodb batch-write-item --request-items file://movies_148.json
aws dynamodb batch-write-item --request-items file://movies_149.json
aws dynamodb batch-write-item --request-items file://movies_150.json
aws dynamodb batch-write-item --request-items file://movies_151.json
aws dynamodb batch-write-item --request-items file://movies_152.json
aws dynamodb batch-write-item --request-items file://movies_153.json
aws dynamodb batch-write-item --request-items file://movies_154.json
aws dynamodb batch-write-item --request-items file://movies_155.json
aws dynamodb batch-write-item --request-items file://movies_156.json
aws dynamodb batch-write-item --request-items file://movies_157.json
aws dynamodb batch-write-item --request-items file://movies_158.json
aws dynamodb batch-write-item --request-items file://movies_159.json
aws dynamodb batch-write-item --request-items file://movies_160.json
aws dynamodb batch-write-item --request-items file://movies_161.json
aws dynamodb batch-write-item --request-items file://movies_162.json
aws dynamodb batch-write-item --request-items file://movies_163.json
aws dynamodb batch-write-item --request-items file://movies_164.json
aws dynamodb batch-write-item --request-items file://movies_165.json
aws dynamodb batch-write-item --request-items file://movies_166.json
aws dynamodb batch-write-item --request-items file://movies_167.json
aws dynamodb batch-write-item --request-items file://movies_168.json
aws dynamodb batch-write-item --request-items file://movies_169.json
aws dynamodb batch-write-item --request-items file://movies_170.json
aws dynamodb batch-write-item --request-items file://movies_171.json
aws dynamodb batch-write-item --request-items file://movies_172.json
aws dynamodb batch-write-item --request-items file://movies_173.json
aws dynamodb batch-write-item --request-items file://movies_174.json
aws dynamodb batch-write-item --request-items file://movies_175.json
aws dynamodb batch-write-item --request-items file://movies_176.json
aws dynamodb batch-write-item --request-items file://movies_177.json
aws dynamodb batch-write-item --request-items file://movies_178.json
aws dynamodb batch-write-item --request-items file://movies_179.json
aws dynamodb batch-write-item --request-items file://movies_180.json
aws dynamodb batch-write-item --request-items file://movies_181.json
aws dynamodb batch-write-item --request-items file://movies_182.json
aws dynamodb batch-write-item --request-items file://movies_183.json
aws dynamodb batch-write-item --request-items file://movies_184.json
aws dynamodb batch-write-item --request-items file://movies_185.json
aws dynamodb batch-write-item --request-items file://movies_186.json
aws dynamodb batch-write-item --request-items file://movies_187.json
aws dynamodb batch-write-item --request-items file://movies_188.json
aws dynamodb batch-write-item --request-items file://movies_189.json
aws dynamodb batch-write-item --request-items file://movies_190.json
aws dynamodb batch-write-item --request-items file://movies_191.json
aws dynamodb batch-write-item --request-items file://movies_192.json
aws dynamodb batch-write-item --request-items file://movies_193.json
aws dynamodb batch-write-item --request-items file://movies_194.json
aws dynamodb batch-write-item --request-items file://movies_195.json
aws dynamodb batch-write-item --request-items file://movies_196.json
aws dynamodb batch-write-item --request-items file://movies_197.json
aws dynamodb batch-write-item --request-items file://movies_198.json
aws dynamodb batch-write-item --request-items file://movies_199.json
aws dynamodb batch-write-item --request-items file://movies_200.json
aws dynamodb batch-write-item --request-items file://movies_201.json
aws dynamodb batch-write-item --request-items file://movies_202.json
aws dynamodb batch-write-item --request-items file://movies_203.json
aws dynamodb batch-write-item --request-items file://movies_204.json
aws dynamodb batch-write-item --request-items file://movies_205.json
aws dynamodb batch-write-item --request-items file://movies_206.json
aws dynamodb batch-write-item --request-items file://movies_207.json
aws dynamodb batch-write-item --request-items file://movies_208.json
aws dynamodb batch-write-item --request-items file://movies_209.json
aws dynamodb batch-write-item --request-items file://movies_210.json
aws dynamodb batch-write-item --request-items file://movies_211.json
aws dynamodb batch-write-item --request-items file://movies_212.json
aws dynamodb batch-write-item --request-items file://movies_213.json
aws dynamodb batch-write-item --request-items file://movies_214.json
aws dynamodb batch-write-item --request-items file://movies_215.json
aws dynamodb batch-write-item --request-items file://movies_216.json
aws dynamodb batch-write-item --request-items file://movies_217.json
aws dynamodb batch-write-item --request-items file://movies_218.json
aws dynamodb batch-write-item --request-items file://movies_219.json
aws dynamodb batch-write-item --request-items file://movies_220.json
aws dynamodb batch-write-item --request-items file://movies_221.json
aws dynamodb batch-write-item --request-items file://movies_222.json
aws dynamodb batch-write-item --request-items file://movies_223.json
aws dynamodb batch-write-item --request-items file://movies_224.json
aws dynamodb batch-write-item --request-items file://movies_225.json
aws dynamodb batch-write-item --request-items file://movies_226.json
aws dynamodb batch-write-item --request-items file://movies_227.json
aws dynamodb batch-write-item --request-items file://movies_228.json
aws dynamodb batch-write-item --request-items file://movies_229.json
aws dynamodb batch-write-item --request-items file://movies_230.json
aws dynamodb batch-write-item --request-items file://movies_231.json
aws dynamodb batch-write-item --request-items file://movies_232.json
aws dynamodb batch-write-item --request-items file://movies_233.json
aws dynamodb batch-write-item --request-items file://movies_234.json
aws dynamodb batch-write-item --request-items file://movies_235.json
aws dynamodb batch-write-item --request-items file://movies_236.json
aws dynamodb batch-write-item --request-items file://movies_237.json
aws dynamodb batch-write-item --request-items file://movies_238.json
aws dynamodb batch-write-item --request-items file://movies_239.json
aws dynamodb batch-write-item --request-items file://movies_240.json
aws dynamodb batch-write-item --request-items file://movies_241.json
aws dynamodb batch-write-item --request-items file://movies_242.json
aws dynamodb batch-write-item --request-items file://movies_243.json
aws dynamodb batch-write-item --request-items file://movies_244.json
aws dynamodb batch-write-item --request-items file://movies_245.json
aws dynamodb batch-write-item --request-items file://movies_246.json
aws dynamodb batch-write-item --request-items file://movies_247.json
aws dynamodb batch-write-item --request-items file://movies_248.json
aws dynamodb batch-write-item --request-items file://movies_249.json
aws dynamodb batch-write-item --request-items file://movies_250.json
aws dynamodb batch-write-item --request-items file://movies_251.json
aws dynamodb batch-write-item --request-items file://movies_252.json
aws dynamodb batch-write-item --request-items file://movies_253.json
aws dynamodb batch-write-item --request-items file://movies_254.json
aws dynamodb batch-write-item --request-items file://movies_255.json
aws dynamodb batch-write-item --request-items file://movies_256.json
aws dynamodb batch-write-item --request-items file://movies_257.json
aws dynamodb batch-write-item --request-items file://movies_258.json
aws dynamodb batch-write-item --request-items file://movies_259.json
aws dynamodb batch-write-item --request-items file://movies_260.json
aws dynamodb batch-write-item --request-items file://movies_261.json
aws dynamodb batch-write-item --request-items file://movies_262.json
aws dynamodb batch-write-item --request-items file://movies_263.json
aws dynamodb batch-write-item --request-items file://movies_264.json
aws dynamodb batch-write-item --request-items file://movies_265.json
aws dynamodb batch-write-item --request-items file://movies_266.json
aws dynamodb batch-write-item --request-items file://movies_267.json
aws dynamodb batch-write-item --request-items file://movies_268.json
aws dynamodb batch-write-item --request-items file://movies_269.json
aws dynamodb batch-write-item --request-items file://movies_270.json
aws dynamodb batch-write-item --request-items file://movies_271.json
aws dynamodb batch-write-item --request-items file://movies_272.json
aws dynamodb batch-write-item --request-items file://movies_273.json
aws dynamodb batch-write-item --request-items file://movies_274.json
aws dynamodb batch-write-item --request-items file://movies_275.json
aws dynamodb batch-write-item --request-items file://movies_276.json
aws dynamodb batch-write-item --request-items file://movies_277.json
aws dynamodb batch-write-item --request-items file://movies_278.json
aws dynamodb batch-write-item --request-items file://movies_279.json
aws dynamodb batch-write-item --request-items file://movies_280.json
aws dynamodb batch-write-item --request-items file://movies_281.json
aws dynamodb batch-write-item --request-items file://movies_282.json
aws dynamodb batch-write-item --request-items file://movies_283.json
aws dynamodb batch-write-item --request-items file://movies_284.json
aws dynamodb batch-write-item --request-items file://movies_285.json
aws dynamodb batch-write-item --request-items file://movies_286.json
aws dynamodb batch-write-item --request-items file://movies_287.json
aws dynamodb batch-write-item --request-items file://movies_288.json
aws dynamodb batch-write-item --request-items file://movies_289.json
aws dynamodb batch-write-item --request-items file://movies_290.json
aws dynamodb batch-write-item --request-items file://movies_291.json
aws dynamodb batch-write-item --request-items file://movies_292.json
aws dynamodb batch-write-item --request-items file://movies_293.json
aws dynamodb batch-write-item --request-items file://movies_294.json
aws dynamodb batch-write-item --request-items file://movies_295.json
aws dynamodb batch-write-item --request-items file://movies_296.json
aws dynamodb batch-write-item --request-items file://movies_297.json
aws dynamodb batch-write-item --request-items file://movies_298.json
aws dynamodb batch-write-item --request-items file://movies_299.json
aws dynamodb batch-write-item --request-items file://movies_300.json
aws dynamodb batch-write-item --request-items file://movies_301.json
aws dynamodb batch-write-item --request-items file://movies_302.json
aws dynamodb batch-write-item --request-items file://movies_303.json
aws dynamodb batch-write-item --request-items file://movies_304.json
aws dynamodb batch-write-item --request-items file://movies_305.json
aws dynamodb batch-write-item --request-items file://movies_306.json
aws dynamodb batch-write-item --request-items file://movies_307.json
aws dynamodb batch-write-item --request-items file://movies_308.json
aws dynamodb batch-write-item --request-items file://movies_309.json
aws dynamodb batch-write-item --request-items file://movies_310.json
aws dynamodb batch-write-item --request-items file://movies_311.json
aws dynamodb batch-write-item --request-items file://movies_312.json
aws dynamodb batch-write-item --request-items file://movies_313.json
aws dynamodb batch-write-item --request-items file://movies_314.json
aws dynamodb batch-write-item --request-items file://movies_315.json
aws dynamodb batch-write-item --request-items file://movies_316.json
aws dynamodb batch-write-item --request-items file://movies_317.json
aws dynamodb batch-write-item --request-items file://movies_318.json
aws dynamodb batch-write-item --request-items file://movies_319.json
aws dynamodb batch-write-item --request-items file://movies_320.json
aws dynamodb batch-write-item --request-items file://movies_321.json
aws dynamodb batch-write-item --request-items file://movies_322.json
aws dynamodb batch-write-item --request-items file://movies_323.json
aws dynamodb batch-write-item --request-items file://movies_324.json
aws dynamodb batch-write-item --request-items file://movies_325.json
aws dynamodb batch-write-item --request-items file://movies_326.json
aws dynamodb batch-write-item --request-items file://movies_327.json
aws dynamodb batch-write-item --request-items file://movies_328.json
aws dynamodb batch-write-item --request-items file://movies_329.json
aws dynamodb batch-write-item --request-items file://movies_330.json
aws dynamodb batch-write-item --request-items file://movies_331.json
aws dynamodb batch-write-item --request-items file://movies_332.json
aws dynamodb batch-write-item --request-items file://movies_333.json
aws dynamodb batch-write-item --request-items file://movies_334.json
aws dynamodb batch-write-item --request-items file://movies_335.json
aws dynamodb batch-write-item --request-items file://movies_336.json
aws dynamodb batch-write-item --request-items file://movies_337.json
aws dynamodb batch-write-item --request-items file://movies_338.json
aws dynamodb batch-write-item --request-items file://movies_339.json
aws dynamodb batch-write-item --request-items file://movies_340.json
aws dynamodb batch-write-item --request-items file://movies_341.json
aws dynamodb batch-write-item --request-items file://movies_342.json
aws dynamodb batch-write-item --request-items file://movies_343.json
aws dynamodb batch-write-item --request-items file://movies_344.json
aws dynamodb batch-write-item --request-items file://movies_345.json
aws dynamodb batch-write-item --request-items file://movies_346.json
aws dynamodb batch-write-item --request-items file://movies_347.json
aws dynamodb batch-write-item --request-items file://movies_348.json
aws dynamodb batch-write-item --request-items file://movies_349.json
aws dynamodb batch-write-item --request-items file://movies_350.json
aws dynamodb batch-write-item --request-items file://movies_351.json
aws dynamodb batch-write-item --request-items file://movies_352.json
aws dynamodb batch-write-item --request-items file://movies_353.json
aws dynamodb batch-write-item --request-items file://movies_354.json
aws dynamodb batch-write-item --request-items file://movies_355.json
aws dynamodb batch-write-item --request-items file://movies_356.json
aws dynamodb batch-write-item --request-items file://movies_357.json
aws dynamodb batch-write-item --request-items file://movies_358.json
aws dynamodb batch-write-item --request-items file://movies_359.json
aws dynamodb batch-write-item --request-items file://movies_360.json
aws dynamodb batch-write-item --request-items file://movies_361.json
aws dynamodb batch-write-item --request-items file://movies_362.json
aws dynamodb batch-write-item --request-items file://movies_363.json
aws dynamodb batch-write-item --request-items file://movies_364.json
aws dynamodb batch-write-item --request-items file://movies_365.json
aws dynamodb batch-write-item --request-items file://movies_366.json
aws dynamodb batch-write-item --request-items file://movies_367.json
aws dynamodb batch-write-item --request-items file://movies_368.json
aws dynamodb batch-write-item --request-items file://movies_369.json
aws dynamodb batch-write-item --request-items file://movies_370.json
aws dynamodb batch-write-item --request-items file://movies_371.json
aws dynamodb batch-write-item --request-items file://movies_372.json
aws dynamodb batch-write-item --request-items file://movies_373.json
aws dynamodb batch-write-item --request-items file://movies_374.json
aws dynamodb batch-write-item --request-items file://movies_375.json
aws dynamodb batch-write-item --request-items file://movies_376.json
aws dynamodb batch-write-item --request-items file://movies_377.json
aws dynamodb batch-write-item --request-items file://movies_378.json
aws dynamodb batch-write-item --request-items file://movies_379.json
aws dynamodb batch-write-item --request-items file://movies_380.json
aws dynamodb batch-write-item --request-items file://movies_381.json
aws dynamodb batch-write-item --request-items file://movies_382.json
aws dynamodb batch-write-item --request-items file://movies_383.json
aws dynamodb batch-write-item --request-items file://movies_384.json
aws dynamodb batch-write-item --request-items file://movies_385.json
aws dynamodb batch-write-item --request-items file://movies_386.json
aws dynamodb batch-write-item --request-items file://movies_387.json
aws dynamodb batch-write-item --request-items file://movies_388.json

aws dynamodb batch-write-item --request-items file://users_0.json
aws dynamodb batch-write-item --request-items file://users_1.json
aws dynamodb batch-write-item --request-items file://users_2.json
aws dynamodb batch-write-item --request-items file://users_3.json
aws dynamodb batch-write-item --request-items file://users_4.json
aws dynamodb batch-write-item --request-items file://users_5.json
aws dynamodb batch-write-item --request-items file://users_6.json
aws dynamodb batch-write-item --request-items file://users_7.json
aws dynamodb batch-write-item --request-items file://users_8.json
aws dynamodb batch-write-item --request-items file://users_9.json
aws dynamodb batch-write-item --request-items file://users_10.json
aws dynamodb batch-write-item --request-items file://users_11.json
aws dynamodb batch-write-item --request-items file://users_12.json
aws dynamodb batch-write-item --request-items file://users_13.json
aws dynamodb batch-write-item --request-items file://users_14.json
aws dynamodb batch-write-item --request-items file://users_15.json
aws dynamodb batch-write-item --request-items file://users_16.json
aws dynamodb batch-write-item --request-items file://users_17.json
aws dynamodb batch-write-item --request-items file://users_18.json
aws dynamodb batch-write-item --request-items file://users_19.json
aws dynamodb batch-write-item --request-items file://users_20.json
aws dynamodb batch-write-item --request-items file://users_21.json
aws dynamodb batch-write-item --request-items file://users_22.json
aws dynamodb batch-write-item --request-items file://users_23.json

aws dynamodb batch-write-item --request-items file://real_users.json