aws dynamodb batch-write-item --request-items file://users_0.json
aws dynamodb batch-write-item --request-items file://users_1.json
aws dynamodb batch-write-item --request-items file://users_2.json
aws dynamodb batch-write-item --request-items file://users_3.json
aws dynamodb batch-write-item --request-items file://users_4.json
aws dynamodb batch-write-item --request-items file://users_5.json
aws dynamodb batch-write-item --request-items file://users_6.json
aws dynamodb batch-write-item --request-items file://users_7.json
aws dynamodb batch-write-item --request-items file://users_8.json
aws dynamodb batch-write-item --request-items file://users_9.json
aws dynamodb batch-write-item --request-items file://users_10.json
aws dynamodb batch-write-item --request-items file://users_11.json
aws dynamodb batch-write-item --request-items file://users_12.json
aws dynamodb batch-write-item --request-items file://users_13.json
aws dynamodb batch-write-item --request-items file://users_14.json
aws dynamodb batch-write-item --request-items file://users_15.json
aws dynamodb batch-write-item --request-items file://users_16.json
aws dynamodb batch-write-item --request-items file://users_17.json
aws dynamodb batch-write-item --request-items file://users_18.json
aws dynamodb batch-write-item --request-items file://users_19.json
aws dynamodb batch-write-item --request-items file://users_20.json
aws dynamodb batch-write-item --request-items file://users_21.json
aws dynamodb batch-write-item --request-items file://users_22.json
aws dynamodb batch-write-item --request-items file://users_23.json