Resources:
    Table:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:service.name}-dynamodb
            AttributeDefinitions:
                - AttributeName: type # premier attribut obligatoire à renseigner quand on ajoute une donnée ("movie" ou "user")
                  AttributeType: S    # c'est un string
                - AttributeName: uuid # deuxieme attribut obligatoire
                  AttributeType: S    # aussi un string, même si c'est un nombre
            KeySchema:
                - AttributeName: type # type est la clé de partition
                  KeyType: HASH
                - AttributeName: uuid # uuid est la clé de tri
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST